color_list_1 = set(["White", "Blue", "Green"])
color_list_2 = set(["White", "Black"])
print("Original set elements:")
print("\nColor List 1:", color_list_1)
print("\nColor List 2:", color_list_2)
print("\nAll colors in Color list 1 but not in Color list 2:")
print(color_list_1.difference(color_list_2))
